### ISSUE TITLE
Any chance you can update the counties from this updated list?

### ISSUE THREAD

**Issue by BlazenWeb** [leewillis77/woocommerce-uk-counties#7]
Although the Royal Mail doesn't need counties any more in the postal address, there's still a need for such a list, thanks for making it. But it doesn't make sense to use a 1996 version of the postal counties from Wikipedia. It doesn't make sense for customers to be asked to put their county as Avon when it's over 20 years ago since people did that - people can get annoyed and we obviously want to reduce friction at checkout.

A more up to date list can be [found here](url=https://gist.github.com/eddturtle/0e92845f26c5b9d57cfd) with postal counties such as City of Bristol, Bath and North East Somerset, South Gloucestershire and not Avon. Any chance you'd be able to update it?

**Comment by leewillis77** [comment]
Hi; 

I'm happy to look at merging a PR to update the list if you believe there is more accurate information (your original report suggested a better link, but didn't actually provide it?). If you are going to raise a PR, you'll need to consider backwards compatibility for people who are already using the existing list, and have data using the existing keys.

**Comment by leewillis77** [comment]
No response. Closing.
